### ISSUE TITLE
Leaves dangling lockfile if conatiner not individually stopped

### ISSUE THREAD

**Issue by Patabugen** [oanhnn/docker-laravel-echo-server#12]
I'm using Docker for Windows and the GUI to start/stop containers. I use Docker-Compose to start a bunch of containers.

If I stop the laravel-echo-server it properly removes the `/app/laravel-echo-server.lock` file.

However if I stop/restart Docker itself (either with the menu option, or as happens when I shut down my PC) the lock file does not get removed.

So I either need to manually stop the laravel-echo-server container or manually remove the lock file.

It'd be good if the server could ignore the lock file if it's booting (since it's a container it can't already have a server running anyway) or do whatever cleanup happens when I stop the container individually, also do that cleanup when I stop the whole of docker (assuming there's a hook available).

From a glance it looks like this issue is fixed by this PR:

https://github.com/oanhnn/docker-laravel-echo-server/pull/11/commits

**Comment by oanhnn** [comment]
Thank @Patabugen 
I merged PR #11 and release v3.1.0
Please confirm your problem with new version.

**Comment by Patabugen** [comment]
Confirmed and working for me! Thanks @oanhnn and @squareborg !

In case it's useful to anyone: I couldn't get docker to grab the new version (probably my lack of knowledge, not a flaw in docker), so I specified the version after the image: `oanhnn/laravel-echo-server:3.1.0`

**Comment by oanhnn** [comment]
@Patabugen From version 3.1.0, i update GitHub workflow to build image follow sematic version.
You should use sematic version (like `3.1.0` or `3.1`) for production. Please see README
