### ISSUE TITLE
Readme docs different from Docker Hub docs

### ISSUE THREAD

**Issue by GregPeden** [oanhnn/docker-laravel-echo-server#16]
I think the documentation on Docker Hub is obsolete.

https://hub.docker.com/r/oanhnn/laravel-echo-server

It says the latest is in 2.x branch, and it lists env variable "REDIS_KEY_PREFIX" vs here in readme where it is called "REDIS_PREFIX".

**Comment by oanhnn** [comment]
I'm sorry. I was update README in Docker hub.
