### ISSUE TITLE
Incomplete environment variable support

### ISSUE THREAD

**Issue by pintoflager** [oanhnn/docker-laravel-echo-server#18]
Hi,

Entrypoint script in `/bin/docker-entrypoint` has only partial support for environment variables
Only following env keys are being looked up and swapped to `laravel-echo-server.json`:

```
LARAVEL_ECHO_SERVER_DB
REDIS_HOST
REDIS_PORT
REDIS_PASSWORD
REDIS_PREFIX
REDIS_DB
```

Other defined environment variables have no impact.

**Comment by oanhnn** [comment]
Yes. The entrypoint script only support partial for these environment variable overrides.
Some environments will support by native laravel-echo-server. It is implemented by code and overrides `laravel-echo-server.json`

See here:

https://github.com/oanhnn/docker-laravel-echo-server#override-config-by-environment-variables
https://github.com/tlaverdure/laravel-echo-server/blob/master/README.md#dotenv
