### ISSUE TITLE
最新的为啥去除了心跳  HEALTHCHECK

### ISSUE THREAD

**Issue by renkx** [oanhnn/docker-laravel-echo-server#19]
看了最新的dockerfile，里面的HEALTHCHECK命令去除了，为啥，原先很好用

Sau khi đọc tệp dockerfile mới nhất, lệnh HEALTHCHECK đã bị xóa. Tại sao, lệnh này rất dễ sử dụng. 

https://github.com/oanhnn/docker-laravel-echo-server/commit/3948e8163bc30daf64a5cb7016411bf558ebc7d4#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L30

**Comment by oanhnn** [comment]
Someone recommend moving HEALTHCHECK from `Dockerfile` to `docker-compose.yml` or K8S configuration file. It like some official images (MySQL, Redis, ...)
