### ISSUE TITLE
这个心跳脚本path参数是写死的

### ISSUE THREAD

**Issue by renkx** [oanhnn/docker-laravel-echo-server#20]
![image](https://user-images.githubusercontent.com/26194193/114684527-90a47a00-9d43-11eb-9242-2d8eca10e83a.png)

这个心跳脚本path参数是写死的
https://github.com/oanhnn/docker-laravel-echo-server/blob/master/bin/health-check#L7

但是 laravel-echo-server.json里面的socketio的path可以自定义
![image](https://user-images.githubusercontent.com/26194193/114684371-6eaaf780-9d43-11eb-97bf-4d597767d0f1.png)

**Comment by oanhnn** [comment]
@rkxs I improved health-check script in v3.1.2 (released a few minutes ago). Your problem was resolved. Please see `examples/sqlite.yml`
