### ISSUE TITLE
REDIS_PREFIX empty not working

### ISSUE THREAD

**Issue by rroblik** [oanhnn/docker-laravel-echo-server#26]
Dear,

When using empty `REDIS_PREFIX` env var (in case of you don't have any prefix) is NOT working when entrypoint script generate the `/app/laravel-echo-server.json` file. 

That's because of use of sed : https://github.com/oanhnn/docker-laravel-echo-server/blob/2f23dfb72b212489b2e53a73b58da27723494db8/bin/docker-entrypoint#L36

Must be fixed, thanks.

**Comment by oanhnn** [comment]
I fixed, Thank you.
