### ISSUE TITLE
Container takes 10s timeout to stop, exits with code 137

### ISSUE THREAD

**Issue by rulatir** [oanhnn/docker-laravel-echo-server#3]
Looks like it isn't handling SIGTERM properly and relies on docker eventually SIGKILLing it?

**Comment by oanhnn** [comment]
Thank you! I need confirm this problem. Can you describe how to reproduce it?

**Comment by oanhnn** [comment]
I close this issue because i can't reproduce it.
Everyone has same problem can re-open it.
