### ISSUE TITLE
[Feature Request]  add  supervisord

### ISSUE THREAD

**Issue by zacksleo** [oanhnn/docker-laravel-echo-server#6]
Maybe It is more useful to add supervisord to keep the server stable.

**Comment by oanhnn** [comment]
I don't think we need `suppervisor`. The proccess should run on process_id 1 and it will control by Docker.

**Comment by oanhnn** [comment]
If you need a stack for laravel + laravel-echo-server, you can find an example in here.

https://github.com/oanhnn/docker-php-stack/blob/master/example-laravel/docker-compose.yml
